### ISSUE TITLE
Thanks for sharing this

### ISSUE THREAD

**Issue by idkjs** [rsbear/prisma-graphql-auth#1]
I tried running this against your demo without luck. 

Following your readme then opening the endpoint,http://localhost:4001/graphql, i get:

```
mutation SignUp {
  signup(email:"test@test.com",name:"test",password:"test"){
    token
  }
}
```

```
{
  "errors": [
    {
      "message": "Project not found: 'default@default'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "signup"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "result": {
            "errors": [
              {
                "message": "Project not found: 'default@default'",
                "code": 3016,
                "requestId": "local:cjvca3384001j0719rg82wxop"
              }
            ],
            "status": 200
          },
          "stacktrace": [
            "Error: Project not found: 'default@default'",
            "    at BatchedGraphQLClient.<anonymous> (/Users/prisc_000/Downloads/prisma-graphql-auth-master/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:69:35)",
            "    at step (/Users/prisc_000/Downloads/prisma-graphql-auth-master/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)",
            "    at Object.next (/Users/prisc_000/Downloads/prisma-graphql-auth-master/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)",
            "    at fulfilled (/Users/prisc_000/Downloads/prisma-graphql-auth-master/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)",
            "    at processTicksAndRejections (internal/process/task_queues.js:86:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "signup": null
  }
}
```

Also gettting a cross-origin error on your frontend. 

Any idea what any of this means?

Thanks for any insight.

**Comment by idkjs** [comment]
I just needed to calm down, I think. 

I neglected to run `prisma deploy`. Thanks
